twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
      - bootstrap_4_layout.html.twig
      - /form/my_form.html.twig
    globals:
      categoryRepository: "@App\\Repository\\CategoryRepository"
      cartService: "@App\\Cart\\CartService"

