# App\Entity\Product:
#   properties:
#     name:
#      - NotBlank: { message: "Name can't be empty" }
#      - Length: { min: 3, max: 255, minMessage: "Name is too short", maxMessage: "Name is too long" }
#     price:
#       - NotBlank: { message: "Price can't be empty" }
#       - Type: { type: "numeric", message: "Price must be numeric" }
